import R1 from '../../img/img_reviews/r1.jpg';
import R2 from '../../img/img_reviews/r2.jpg';
import R3 from '../../img/img_reviews/r3.jpg';
import R4 from '../../img/img_reviews/r4.jpg';
import R5 from '../../img/img_reviews/r5.jpg';
import R6 from '../../img/img_reviews/r6.jpg';
import R7 from '../../img/img_reviews/r7.jpg';
import R8 from '../../img/img_reviews/r8.jpg';
import R9 from '../../img/img_reviews/r9.jpg';
import R10 from '../../img/img_reviews/r10.jpg';
import R11 from '../../img/img_reviews/r1.jpg';
import R12 from '../../img/img_reviews/r12.jpg';
import R13 from '../../img/img_reviews/r13.jpg';
import R14 from '../../img/img_reviews/r14.jpg';
import R15 from '../../img/img_reviews/r15.jpg';
import R16 from '../../img/img_reviews/r16.jpg';
import R17 from '../../img/img_reviews/r17.jpg';
import R18 from '../../img/img_reviews/r18.jpg';

export const dataImgRew = [R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,R11,R12,R13,R14,R15,R16,R17,R18];